### ISSUE TITLE
Doppio doesn't compile in TypeScript 2.2

### ISSUE THREAD

**Issue by DanielRough** [plasma-umass/doppio#493]
Hi, I'm having trouble with running 'npm install' I have all the prerequisites (JDK 8, npm, node, grunt-cli) but towards the end of npm install I get this failure message:

> Using tsc v2.2.1
> src/gLong.ts(35,30): error TS2448: Block-scoped variable 'fromInt' used before its declaration.
> src/gLong.ts(36,29): error TS2448: Block-scoped variable 'fromInt' used before its declaration.
> src/gLong.ts(37,33): error TS2448: Block-scoped variable 'fromInt' used before its declaration.
> src/gLong.ts(38,35): error TS2448: Block-scoped variable 'fromBits' used before its declaration.
> src/gLong.ts(39,35): error TS2448: Block-scoped variable 'fromBits' used before its declaration.
> src/gLong.ts(40,38): error TS2448: Block-scoped variable 'fromInt' used before its declaration.
> 
> >> 6 non-emit-preventing type warnings  
> >> Error: tsc return code: 2
> Warning: Task "ts:dev-cli" failed. Use --force to continue.
> 
> Aborted due to warnings.

I'm on Ubuntu 16 if that makes any difference, and attach my debug log.
[npm-debug.txt](https://github.com/plasma-umass/doppio/files/826727/npm-debug.txt)

Thanks for looking!

**Comment by jvilk** [comment]
Ah, looks like Doppio doesn't compile in TypeScript 2.2.

A workaround is to run `npm install typescript@2.0.3` in the doppio folder to install a compatible version. Let me know if that doesn't work.

**Comment by DanielRough** [comment]
Thank you for your quick reply!
Unfortunately I'm now faced with a syntax error. 

> Running "ts:dev-cli" (ts) task
> Compiling...
> Using tsc v2.0.3
> node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.
> 
> >> 1 syntax error  
> >> Error: tsc return code: 2

Log attached below. Please could you advise? Thank you!

[npm-debug.txt](https://github.com/plasma-umass/doppio/files/828408/npm-debug.txt)

**Comment by jvilk** [comment]
I really need to switch to using Yarn to lock down these package versions. :-)

My assumption: `@types/jasmine` is also a newer version that relies on a newer version of TypeScript. [The last version I explicitly installed was 2.5.35](https://github.com/plasma-umass/doppio/blob/master/package.json#L29), so maybe an `npm install @types/jasmine@2.5.35` will fix it?

I'll look at all of these package-version-related issues later on tonight. Sorry for the inconvenience!

**Comment by DanielRough** [comment]
The minor inconvenience of package version issues is more than compensated for by the convenience of doppio :D

Suffice to say that did the trick! I look forward to working with it, thanks again. :-)

**Comment by jvilk** [comment]
Should now be fixed in master.
